//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseLogs
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSystemInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileSystemInfo()
        {
            this.ChildrenInfos = new HashSet<FileSystemInfo>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public int Parent { get; set; }
        public System.DateTime CreationTimeUTC { get; set; }
        public long Attributes { get; set; }
        public System.DateTime LastAccessTimeUTC { get; set; }
        public System.DateTime LastWriteTimeUTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileSystemInfo> ChildrenInfos { get; set; }
        public virtual FileSystemInfo ParentInfo { get; set; }
    }
}
